### PR TITLE
Optimising the minimum function for speed : revert to min(a,b)

### PR DESCRIPTION
**Pull request by psadac**
name              old time/op    new time/op    delta
Simple/ASCII-4       471ns ± 1%     393ns ± 2%  -16.44%  (p=0.000 n=25+28)
Simple/French-4      842ns ± 2%     719ns ± 1%  -14.66%  (p=0.000 n=28+30)
Simple/Nordic-4     1.67µs ± 1%    1.43µs ± 0%  -14.59%  (p=0.000 n=28+28)
Simple/Tibetan-4    1.31µs ± 1%    1.15µs ± 1%  -12.15%  (p=0.000 n=27+29)
[Geo mean]           966ns          826ns       -14.48%

name              old alloc/op   new alloc/op   delta
Simple/ASCII-4       96.0B ± 0%     96.0B ± 0%     ~     (all equal)
Simple/French-4       128B ± 0%      128B ± 0%     ~     (all equal)
Simple/Nordic-4       192B ± 0%      192B ± 0%     ~     (all equal)
Simple/Tibetan-4      144B ± 0%      144B ± 0%     ~     (all equal)
[Geo mean]            136B           136B        +0.00%

name              old allocs/op  new allocs/op  delta
Simple/ASCII-4        1.00 ± 0%      1.00 ± 0%     ~     (all equal)
Simple/French-4       1.00 ± 0%      1.00 ± 0%     ~     (all equal)
Simple/Nordic-4       1.00 ± 0%      1.00 ± 0%     ~     (all equal)
Simple/Tibetan-4      1.00 ± 0%      1.00 ± 0%     ~     (all equal)
[Geo mean]            1.00           1.00        +0.00%

### CODE REVIEW

**Comment by psadac** [comment]
Hello Agniva,
changing the function min(a, b, c) to min(a, b) seems to have a great impact on ComputeDistance() performance.
I am a newbie in Go, so there may be something wrong with what i have done : 
`for i in {0..29}; do make bench >> [old,new].txt; done`
then : 
`benchstat -geomean old.txt new.txt`

**Comment by agnivade** [comment]
This is really surprising ! I checked it, and I see it too.

FYI, you do not need to do this - `for i in {0..29}; do make bench >> [old,new].txt; done`. You can specify the `-count` parameter in `go test` itself. That is more idiomatic.

I would like to see the assembly output and see why we are seeing this gain. If you have some time, you can get the assembly output and paste it here. Or I would do it myself in some time.

**Comment by psadac** [comment]
I have generated the assembly output  : 
`go tool compile -S levenshtein.go > [old,new].s`
and compared the relevant portion of the previous version : 
>         cmpq    R13, AX
>         jcc     659
>         movq    -8(CX)(R10*8), R11
>         cmpq    R10, AX
>         jcc     659
>         incq    R11
>         leaq    1(R8), R12
>         movq    (CX)(R10*8), R14
>         incq    R14
>         cmpq    R11, R12
>         jge     445
>         cmpq    R11, R14
>         jlt     383
>         movq    R14, R11
>         jmp     383
>         cmpq    R12, R14
>         jge     440
>         movq    R12, R11
>         jmp     383
with the new one (using the [Compiler Explorer](https://godbolt.org/)) : 
>         cmpq    R13, AX
>         jcc     651
>         movq    -8(CX)(R10*8), R11
>         incq    R11
>         leaq    1(R8), R12
>         cmpq    R11, R12
>         cmovqlt R11, R12
>         cmpq    R10, AX
>         jcc     651
>         movq    (CX)(R10*8), R14
>         leaq    1(R14), R11
>         cmpq    R12, R11
>         cmovqlt R12, R11
>         jmp     383
my understanding in assembly is basic but i think that : 
-  `min()` functions are inlined in both versions
-  SSA compiler has generated optimised `cmovqlt` instructions in the new version (`cmovqlt` is present in go source code file `.../ssa/rewriteAMD64.go`)
- there are less jumps in the newer version (3 vs 7) so the flow in the instruction pipeline of the processor is probably optimised

Thank you for help, i didnt know the `-count` parameter, and feel free correct me if i made incorrect assumptions.

**Comment by agnivade** [comment]
Ah it's the CMOV instruction ! That got newly added in 1.11. LGTM.

**Pull request merged**
